# Generated by Django 5.1.15 on 2026-02-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=50)),
                (
                    "line_id",
                    models.CharField(blank=True, help_text="LINE ID", max_length=100),
                ),
                (
                    "marketing_opt_in",
                    models.BooleanField(
                        default=False, help_text="Agreed to receive marketing emails"
                    ),
                ),
                ("opted_in_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags for segmentation, e.g. 'japan-interest,repeat-customer'",
                        max_length=500,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this customer"
                    ),
                ),
                ("total_inquiries", models.PositiveIntegerField(default=0)),
                ("total_bookings", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
