# Generated by Django 5.1.15 on 2026-02-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["-created_at"], name="customers_c_created_73c55e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["marketing_opt_in"], name="customers_c_marketi_5c905e_idx"
            ),
        ),
    ]
