[build]
builder = "nixpacks"
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
startCommand = "python manage.py migrate && python manage.py createsuperuser --noinput --username admin --email admin@smilememory.com 2>/dev/null; gunicorn config.wsgi --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
