# Generated by Django 5.1.15 on 2026-02-24 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="IATA code e.g. TG, CX", max_length=10, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_th", models.CharField(blank=True, max_length=200)),
                ("logo", models.ImageField(blank=True, upload_to="airlines/")),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("name_th", models.CharField(blank=True, max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="CSS class or emoji", max_length=50
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("name_th", models.CharField(blank=True, max_length=200)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                (
                    "country_code_iso2",
                    models.CharField(
                        blank=True, help_text="ISO 3166-1 alpha-2", max_length=2
                    ),
                ),
                (
                    "country_code_iso3",
                    models.CharField(
                        blank=True, help_text="ISO 3166-1 alpha-3", max_length=3
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("description_th", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="destinations/")),
                ("is_featured", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="tours.destination",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("title_th", models.CharField(blank=True, max_length=300)),
                ("slug", models.SlugField(max_length=350, unique=True)),
                (
                    "product_code",
                    models.CharField(
                        blank=True,
                        help_text="Wholesaler tour code e.g. ZGHKG-2413CX",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "highlight",
                    models.TextField(blank=True, help_text="Tour highlights text"),
                ),
                ("highlight_th", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("description_th", models.TextField(blank=True)),
                ("short_description", models.CharField(blank=True, max_length=500)),
                ("short_description_th", models.CharField(blank=True, max_length=500)),
                (
                    "locations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="City names visited e.g. ['Tokyo', 'Osaka', 'Kyoto']",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "price_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Lowest adult double-occupancy price across departures",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="THB", max_length=3)),
                ("duration_days", models.PositiveIntegerField(blank=True, null=True)),
                ("duration_nights", models.PositiveIntegerField(blank=True, null=True)),
                ("hotel_stars_min", models.PositiveIntegerField(blank=True, null=True)),
                ("hotel_stars_max", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "plane_meals",
                    models.BooleanField(
                        default=False, help_text="In-flight meals included"
                    ),
                ),
                (
                    "total_meals",
                    models.PositiveIntegerField(
                        blank=True, help_text="Total meals in tour", null=True
                    ),
                ),
                (
                    "includes",
                    models.TextField(blank=True, help_text="What is included"),
                ),
                ("includes_th", models.TextField(blank=True)),
                (
                    "excludes",
                    models.TextField(blank=True, help_text="What is not included"),
                ),
                ("excludes_th", models.TextField(blank=True)),
                (
                    "hero_image",
                    models.ImageField(blank=True, upload_to="tours/heroes/"),
                ),
                (
                    "hero_image_url",
                    models.URLField(
                        blank=True, help_text="External image URL from wholesaler"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, upload_to="tours/thumbnails/"),
                ),
                ("pdf_file", models.FileField(blank=True, upload_to="tours/pdfs/")),
                (
                    "pdf_url",
                    models.URLField(
                        blank=True, help_text="External PDF URL from wholesaler"
                    ),
                ),
                (
                    "word_url",
                    models.URLField(
                        blank=True, help_text="External Word doc URL from wholesaler"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Wholesaler name e.g. Zego",
                        max_length=100,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, help_text="Product ID from source", max_length=200
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                (
                    "airline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tours",
                        to="tours.airline",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="tours", to="tours.category"
                    ),
                ),
                (
                    "destinations",
                    models.ManyToManyField(
                        related_name="tours", to="tours.destination"
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("name_th", models.CharField(blank=True, max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="THB", max_length=3)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_options",
                        to="tours.tour",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ItineraryDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=300)),
                ("title_th", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField()),
                ("description_th", models.TextField(blank=True)),
                (
                    "breakfast",
                    models.CharField(blank=True, help_text="Y/N/P/C", max_length=1),
                ),
                ("breakfast_description", models.CharField(blank=True, max_length=300)),
                (
                    "lunch",
                    models.CharField(blank=True, help_text="Y/N/P/C", max_length=1),
                ),
                ("lunch_description", models.CharField(blank=True, max_length=300)),
                (
                    "dinner",
                    models.CharField(blank=True, help_text="Y/N/P/C", max_length=1),
                ),
                ("dinner_description", models.CharField(blank=True, max_length=300)),
                ("hotel_name", models.CharField(blank=True, max_length=300)),
                ("hotel_stars", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerary_days",
                        to="tours.tour",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number"],
            },
        ),
        migrations.CreateModel(
            name="TourDeparture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period_code",
                    models.CharField(
                        blank=True,
                        help_text="Group code e.g. TFU-250320R-VZ",
                        max_length=50,
                    ),
                ),
                (
                    "bus",
                    models.CharField(
                        blank=True, help_text="Bus designation (A, B, C)", max_length=10
                    ),
                ),
                ("departure_date", models.DateField()),
                ("return_date", models.DateField()),
                (
                    "departure_airport",
                    models.CharField(
                        blank=True,
                        help_text="e.g. SUVARNABHUMI, DONMUEANG",
                        max_length=100,
                    ),
                ),
                ("group_size", models.PositiveIntegerField(blank=True, null=True)),
                ("booked", models.PositiveIntegerField(default=0)),
                ("seats_available", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("soldout", "Sold Out"),
                            ("waitlist", "Waitlist"),
                            ("closed", "Close Group"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "price_adult",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Adult double occupancy",
                        max_digits=12,
                    ),
                ),
                (
                    "price_child",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Child with bed",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "price_child_no_bed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_infant",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_join_land",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Land only, no flights",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "price_single_supplement",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Extra for single room",
                        max_digits=12,
                    ),
                ),
                (
                    "price_twin_upgrade",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "price_double_upgrade",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "price_triple_upgrade",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "price_single_visa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "price_group_visa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "price_express_visa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "commission_agent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "commission_sale",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "price_adult_promo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Promotional price, 0 = no promo",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "price_child_promo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("external_period_id", models.CharField(blank=True, max_length=200)),
                (
                    "airline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tours.airline",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departures",
                        to="tours.tour",
                    ),
                ),
            ],
            options={
                "ordering": ["departure_date"],
            },
        ),
        migrations.CreateModel(
            name="TourFlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("flight_number", models.CharField(max_length=20)),
                ("route", models.CharField(help_text="e.g. BKK-NRT", max_length=50)),
                ("departure_time", models.TimeField()),
                ("arrival_time", models.TimeField()),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "airline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tours.airline",
                    ),
                ),
                (
                    "departure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flights",
                        to="tours.tourdeparture",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="TourImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(blank=True, upload_to="tours/gallery/")),
                (
                    "image_url",
                    models.URLField(blank=True, help_text="External image URL"),
                ),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("caption_th", models.CharField(blank=True, max_length=300)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="tours.tour",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddIndex(
            model_name="tour",
            index=models.Index(
                fields=["status", "is_featured"], name="tours_tour_status_364be1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tour",
            index=models.Index(
                fields=["source", "external_id"], name="tours_tour_source_356c7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tour",
            index=models.Index(
                fields=["product_code"], name="tours_tour_product_e68b77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tour",
            index=models.Index(fields=["slug"], name="tours_tour_slug_a32940_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="itineraryday",
            unique_together={("tour", "day_number")},
        ),
        migrations.AddIndex(
            model_name="tourdeparture",
            index=models.Index(
                fields=["departure_date", "status"],
                name="tours_tourd_departu_71176d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tourdeparture",
            index=models.Index(
                fields=["tour", "departure_date"], name="tours_tourd_tour_id_ef779e_idx"
            ),
        ),
    ]
