# Generated by Django 5.1.15 on 2026-02-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tour",
            index=models.Index(
                fields=["status", "price_from"], name="tours_tour_status_4c9033_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tour",
            index=models.Index(
                fields=["status", "-created_at"], name="tours_tour_status_adce32_idx"
            ),
        ),
    ]
