# Generated by Django 5.1.15 on 2026-02-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_tours_tour_status_4c9033_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
