"""Thai name mappings for Destination, Category, and Airline models.

Used by:
- apps/tours/management/commands/fill_th_translations.py
- apps/importer/pipeline.py (auto-fill on create)
"""

DESTINATION_TH = {
    "America": "อเมริกา",
    "Australia": "ออสเตรเลีย",
    "China": "จีน",
    "Egypt": "อียิปต์",
    "England": "อังกฤษ",
    "Europe": "ยุโรป",
    "France": "ฝรั่งเศส",
    "Georgia": "จอร์เจีย",
    "Hong Kong": "ฮ่องกง",
    "Hungary": "ฮังการี",
    "India": "อินเดีย",
    "Italy": "อิตาลี",
    "Japan": "ญี่ปุ่น",
    "Jordan": "จอร์แดน",
    "Kazakhstan": "คาซัคสถาน",
    "Macao": "มาเก๊า",
    "Nepal": "เนปาล",
    "Philippines": "ฟิลิปปินส์",
    "Scandinavia": "สแกนดิเนเวีย",
    "Singapore": "สิงคโปร์",
    "South Africa": "แอฟริกาใต้",
    "South Korea": "เกาหลีใต้",
    "Switzerland": "สวิตเซอร์แลนด์",
    "Taiwan": "ไต้หวัน",
    "Turkey": "ตุรกี",
    "Turkiye": "ตุรกี",
    "Vietnam": "เวียดนาม",
    "Thailand": "ไทย",
    "Cambodia": "กัมพูชา",
    "Laos": "ลาว",
    "Myanmar": "เมียนมาร์",
    "Malaysia": "มาเลเซีย",
    "Indonesia": "อินโดนีเซีย",
    "Bali": "บาหลี",
    "Phuket": "ภูเก็ต",
    "Chiang Mai": "เชียงใหม่",
    "Krabi": "กระบี่",
    "Dubai": "ดูไบ",
    "Maldives": "มัลดีฟส์",
    "Sri Lanka": "ศรีลังกา",
    "Bangladesh": "บังกลาเทศ",
    "Pakistan": "ปากีสถาน",
    "Russia": "รัสเซีย",
    "Greece": "กรีซ",
    "Spain": "สเปน",
    "Portugal": "โปรตุเกส",
    "Germany": "เยอรมนี",
    "Austria": "ออสเตรีย",
    "Czech Republic": "สาธารณรัฐเช็ก",
    "Czechia": "เช็กเกีย",
    "Netherlands": "เนเธอร์แลนด์",
    "Belgium": "เบลเยียม",
    "Poland": "โปแลนด์",
    "Croatia": "โครเอเชีย",
    "Iceland": "ไอซ์แลนด์",
    "Norway": "นอร์เวย์",
    "Sweden": "สวีเดน",
    "Finland": "ฟินแลนด์",
    "Denmark": "เดนมาร์ก",
    "United Kingdom": "สหราชอาณาจักร",
    "Scotland": "สกอตแลนด์",
    "Ireland": "ไอร์แลนด์",
    "Morocco": "โมร็อกโก",
    "Kenya": "เคนยา",
    "Tanzania": "แทนซาเนีย",
    "South America": "อเมริกาใต้",
    "Brazil": "บราซิล",
    "Peru": "เปรู",
    "Mexico": "เม็กซิโก",
    "Canada": "แคนาดา",
    "New Zealand": "นิวซีแลนด์",
    "Uzbekistan": "อุซเบกิสถาน",
    "Azerbaijan": "อาเซอร์ไบจาน",
    "Armenia": "อาร์เมเนีย",
    "Israel": "อิสราเอล",
    "Saudi Arabia": "ซาอุดีอาระเบีย",
    "Qatar": "กาตาร์",
    "Oman": "โอมาน",
    "Bhutan": "ภูฏาน",
    "Tibet": "ทิเบต",
    "Mongolia": "มองโกเลีย",
}

CATEGORY_TH = {
    "Adventure": "ผจญภัย",
    "Beach": "ชายหาด",
    "City": "เมือง",
    "Cultural": "วัฒนธรรม",
    "Food & Wine": "อาหารและไวน์",
    "Luxury": "หรูหรา",
    "Nature": "ธรรมชาติ",
    "Shopping": "ช้อปปิ้ง",
    "Honeymoon": "ฮันนีมูน",
    "Family": "ครอบครัว",
    "Group Tour": "ทัวร์กรุ๊ป",
    "Private Tour": "ทัวร์ส่วนตัว",
    "Budget": "ประหยัด",
    "Cruise": "ล่องเรือ",
    "Ski & Snow": "สกีและหิมะ",
}

AIRLINE_TH = {
    "Thai Airways": "การบินไทย",
    "Thai Lion Air": "ไทยไลออนแอร์",
    "Bangkok Airways": "บางกอกแอร์เวย์ส",
    "AirAsia": "แอร์เอเชีย",
    "Thai AirAsia": "ไทยแอร์เอเชีย",
    "Nok Air": "นกแอร์",
    "VietJet Air": "เวียตเจ็ทแอร์",
    "Korean Air": "โคเรียนแอร์",
    "Asiana Airlines": "อาซีอาน่าแอร์ไลน์ส",
    "Japan Airlines": "เจแปนแอร์ไลน์ส",
    "All Nippon Airways": "ออลนิปปอนแอร์เวย์ส",
    "ANA": "เอเอ็นเอ",
    "JAL": "เจเอแอล",
    "Cathay Pacific": "คาเธ่ย์แปซิฟิก",
    "Singapore Airlines": "สิงคโปร์แอร์ไลน์ส",
    "Malaysia Airlines": "มาเลเซียแอร์ไลน์ส",
    "Eva Air": "อีวาแอร์",
    "China Airlines": "ไชน่าแอร์ไลน์ส",
    "China Eastern": "ไชน่าอีสเทิร์น",
    "China Southern": "ไชน่าเซาเทิร์น",
    "Air China": "แอร์ไชน่า",
    "Emirates": "เอมิเรตส์",
    "Qatar Airways": "กาตาร์แอร์เวย์ส",
    "Turkish Airlines": "เตอร์กิชแอร์ไลน์ส",
    "Etihad Airways": "เอทิฮัดแอร์เวย์ส",
    "Lufthansa": "ลุฟท์ฮันซา",
    "Air France": "แอร์ฟรองซ์",
    "British Airways": "บริติชแอร์เวย์ส",
    "Swiss International": "สวิสอินเตอร์เนชันแนล",
    "Royal Jordanian": "รอยัลจอร์แดเนียน",
    "IndiGo": "อินดิโก้",
    "Air India": "แอร์อินเดีย",
    "Scoot": "สกู๊ต",
    "Jeju Air": "เจจูแอร์",
    "Jin Air": "จินแอร์",
    "T'way Air": "ทีเวย์แอร์",
    "Philippine Airlines": "ฟิลิปปินส์แอร์ไลน์ส",
    "Cebu Pacific": "เซบูแปซิฟิก",
    "Garuda Indonesia": "การูด้าอินโดนีเซีย",
    "Vietnam Airlines": "เวียตนามแอร์ไลน์ส",
    "Bamboo Airways": "แบมบูแอร์เวย์ส",
    "Finnair": "ฟินแอร์",
    "SAS": "เอสเอเอส",
    "Various Airlines": "หลายสายการบิน",
    "TBA": "ยังไม่กำหนด",
    # IATA codes (stored by scraper imports)
    "3U": "เสฉวนแอร์ไลน์ส",
    "5J": "เซบูแปซิฟิก",
    "AI": "แอร์อินเดีย",
    "AQ": "9 แอร์",
    "BR": "อีวาแอร์",
    "CA": "แอร์ไชน่า",
    "CI": "ไชน่าแอร์ไลน์ส",
    "CZ": "ไชน่าเซาเทิร์น",
    "DR": "รุยลี่แอร์ไลน์ส",
    "E9": "อีเอ็นไอแอร์",
    "ET": "เอธิโอเปียนแอร์ไลน์ส",
    "EU": "เฉิงตูแอร์ไลน์ส",
    "EY": "เอทิฮัดแอร์เวย์ส",
    "FD": "ไทยแอร์เอเชีย",
    "FM": "เซี่ยงไฮ้แอร์ไลน์ส",
    "GF": "กัลฟ์แอร์",
    "GJ": "กรีนแลนด์แอร์",
    "HO": "จุนเหยาแอร์ไลน์ส",
    "HU": "ไหหนานแอร์ไลน์ส",
    "HX": "ฮ่องกงแอร์ไลน์ส",
    "JX": "สตาร์ลักซ์แอร์ไลน์ส",
    "KC": "แอร์อัสตาน่า",
    "KY": "คุนหมิงแอร์ไลน์ส",
    "LX": "สวิสอินเตอร์เนชันแนล",
    "MM": "พีชแอวิเอชัน",
    "MU": "ไชน่าอีสเทิร์น",
    "NH": "ออลนิปปอนแอร์เวย์ส",
    "NX": "แอร์มาเก๊า",
    "OS": "ออสเตรียนแอร์ไลน์ส",
    "OZ": "อาซีอาน่าแอร์ไลน์ส",
    "QR": "กาตาร์แอร์เวย์ส",
    "QW": "บลูวิงแอร์ไลน์ส",
    "RJ": "รอยัลจอร์แดเนียน",
    "SC": "ชานตงแอร์ไลน์ส",
    "SQ": "สิงคโปร์แอร์ไลน์ส",
    "SV": "เซาดี",
    "UQ": "ยูเนี่ยนแอร์",
    "VJ": "เวียตเจ็ทแอร์",
    "VN": "เวียตนามแอร์ไลน์ส",
    "XJ": "ไทยแอร์เอเชียเอ็กซ์",
}
