# Generated by Django 5.1.15 on 2026-02-24 19:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this import", max_length=300
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("zego", "Zego Travel"),
                            ("gs25", "GS25 Travel"),
                            ("go365", "Go365 Travel"),
                            ("manual", "Manual Upload"),
                            ("other", "Other"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("excel", "Excel (.xlsx/.xls)"),
                            ("csv", "CSV (.csv)"),
                            ("pdf", "PDF (.pdf)"),
                            ("html", "HTML (web page)"),
                            ("api", "API"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "uploaded_file",
                    models.FileField(blank=True, upload_to="imports/%Y/%m/"),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, help_text="URL for HTML/API imports"),
                ),
                (
                    "field_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Column/field mapping: {source_field: django_field}",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("parsing", "Parsing File"),
                            ("mapping", "Mapping Fields"),
                            ("importing", "Importing Data"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partially Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("rows_created", models.PositiveIntegerField(default=0)),
                ("rows_updated", models.PositiveIntegerField(default=0)),
                ("rows_skipped", models.PositiveIntegerField(default=0)),
                ("rows_failed", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("parsed_preview", models.JSONField(blank=True, default=list)),
                ("parsed_headers", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("success", "Success"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Original row data"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="importer.importjob",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number", "created_at"],
            },
        ),
    ]
