# Generated by Django 5.1.15 on 2026-02-25 14:52

from django.db import migrations


def mark_stuck_jobs_failed(apps, _schema_editor):
    ImportJob = apps.get_model("importer", "ImportJob")
    stuck = ImportJob.objects.filter(status__in=["importing", "parsing", "mapping"])
    count = stuck.update(
        status="failed",
        error_message="Interrupted — process was killed before completion (e.g. container restart).",
    )
    if count:
        print(f"  Marked {count} stuck ImportJob(s) as failed.")


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0002_alter_importjob_source"),
    ]

    operations = [
        migrations.RunPython(mark_stuck_jobs_failed, migrations.RunPython.noop),
    ]
