# Generated by Django 5.1.15 on 2026-02-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0003_cleanup_stuck_importjobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importjob",
            name="uploaded_file",
            field=models.FileField(
                blank=True, max_length=500, upload_to="imports/%Y/%m/"
            ),
        ),
    ]
