# Generated by Django 5.1.15 on 2026-02-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="Smile Memory", max_length=200)),
                (
                    "admin_email",
                    models.EmailField(default="admin@smilememory.com", max_length=254),
                ),
                ("phone_number", models.CharField(blank=True, max_length=50)),
                ("whatsapp_number", models.CharField(blank=True, max_length=50)),
                (
                    "line_id",
                    models.CharField(blank=True, help_text="LINE @ ID", max_length=100),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("address_th", models.TextField(blank=True)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_description_th", models.TextField(blank=True)),
                (
                    "bank_account_info",
                    models.TextField(blank=True, help_text="Bank transfer details"),
                ),
                ("bank_account_info_th", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
    ]
