# Generated by Django 5.1.15 on 2026-04-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="admin_email",
            field=models.EmailField(
                default="admin@smilememorytravel.com", max_length=254
            ),
        ),
    ]
