# Generated by Django 5.1.15 on 2026-02-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["status", "category"], name="blog_blogpo_status_ca9ebd_idx"
            ),
        ),
    ]
