# Generated by Django 5.1.15 on 2026-02-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("subject", models.CharField(max_length=300)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=500)),
                ("question_th", models.CharField(blank=True, max_length=500)),
                ("answer", models.TextField()),
                ("answer_th", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("title_th", models.CharField(blank=True, max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("subtitle_th", models.CharField(blank=True, max_length=300)),
                ("image", models.ImageField(blank=True, upload_to="heroes/")),
                (
                    "image_url",
                    models.URLField(blank=True, help_text="External image URL"),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True, default="Explore Tours", max_length=100
                    ),
                ),
                ("cta_text_th", models.CharField(blank=True, max_length=100)),
                ("cta_url", models.CharField(default="/tours/", max_length=300)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("name_th", models.CharField(blank=True, max_length=200)),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="e.g. Bangkok, Thailand", max_length=200
                    ),
                ),
                ("avatar", models.ImageField(blank=True, upload_to="testimonials/")),
                ("quote", models.TextField()),
                ("quote_th", models.TextField(blank=True)),
                (
                    "tour_name",
                    models.CharField(
                        blank=True, help_text="Tour they went on", max_length=300
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(default=5, help_text="1-5 stars"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="TrustBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "icon",
                    models.CharField(help_text="CSS class or emoji", max_length=50),
                ),
                ("value", models.CharField(help_text="e.g. 10,000+", max_length=50)),
                ("label", models.CharField(max_length=100)),
                ("label_th", models.CharField(blank=True, max_length=100)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
