# Generated by Django 5.1.15 on 2026-02-24 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("tours", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("num_adults", models.PositiveIntegerField(default=1)),
                ("num_children", models.PositiveIntegerField(default=0)),
                ("num_infants", models.PositiveIntegerField(default=0)),
                (
                    "room_preference",
                    models.CharField(
                        blank=True, help_text="e.g. double, twin, single", max_length=50
                    ),
                ),
                ("special_requests", models.TextField(blank=True)),
                ("contact_name", models.CharField(max_length=200)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("marketing_opt_in", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "quoted_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total quoted price",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated booking reference e.g. SM-20260224-001",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin staff member handling this inquiry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="customers.customer",
                    ),
                ),
                (
                    "departure",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific departure date if selected",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to="tours.tourdeparture",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to="tours.tour",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InquiryNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("note", models.TextField()),
                (
                    "is_email_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Was this note sent as email to customer?",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="bookings.inquiry",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                fields=["status", "-created_at"], name="bookings_in_status_0decff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                fields=["customer"], name="bookings_in_custome_8da293_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                fields=["reference_number"], name="bookings_in_referen_ed3fa9_idx"
            ),
        ),
    ]
