# Generated by Django 5.1.15 on 2026-02-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("th", "Thai")],
                default="th",
                help_text="Language active when inquiry was submitted",
                max_length=5,
            ),
        ),
    ]
